{
 "title": "Visualization of Visualizations",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app_kubernetes_io_name",
    "label": "Application",
    "query": "label_values(jvm_memory_max_bytes{app_kubernetes_io_name=~\"job.*\"},app_kubernetes_io_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_max_bytes{app_kubernetes_io_name=~\"job.*\"}, instance)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_labels{label_app_kubernetes_io_name=~\"job.*\"}, pod)"
   },
   {
    "name": "kubernetes_node",
    "label": "Node",
    "query": "label_values(kube_pod_labels{label_app_kubernetes_io_name=~\"job.*\"}, kubernetes_node)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Of Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_labels{label_app_kubernetes_io_name=~\"job.*\"}) by (label_app_kubernetes_io_name)",
     "legendFormat": "{{ label_app_kubernetes_io_name }}"
    }
   ]
  },
  {
   "title": "Nodes in Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "description": "Total allocatable CPU in Cluster",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "% of Total CPU Used by Jobs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{namespace=\"upchain-jobs\"}) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total allocatable bytes in Cluster",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "% of Total Memory Used by Jobs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{namespace=\"upchain-jobs\"}) / sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  { "title": "Jobs Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Jobs Pods Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{pod=~\"create.*\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "% of Jobs Successfully completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (jobType) (rate(job_monitor_jobs_counter{exitCode=\"0\"}[5m])) / sum by (jobType ) (rate(job_monitor_jobs_counter[5m]))",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Min Job Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min (job_monitor_jobs_duration_gauge)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Top 5 CPU consuming Job Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{pod_name=~\"create.*\"}[2m])) by (pod_name, container_name))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Top 5 Mem consuming Job Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, container_memory_usage_bytes{pod_name=~\"create.*\"})",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Max CPU Used",
   "type": "stat",
   "description": "Maximum CPU used by a specific job",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod_name=~\"create.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Max Memory Used",
   "type": "stat",
   "description": "Maximum memory used by any specific jobs",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod_name=~\"create.*\"})"
    }
   ]
  },
  {
   "title": "Max Job Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max (job_monitor_jobs_duration_gauge)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  { "title": "Dispatcher Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Incoming Messages Processed per minute",
   "type": "graph",
   "description": "Messages from App Server",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (messageStatus) (rate(job_dispatcher_messages_processed[1m])) * 60",
     "legendFormat": "{{ messageStatus }}"
    }
   ]
  },
  {
   "title": "Jobs submitted per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (jobType) (rate(job_dispatcher_jobs_created[1m])) * 60",
     "legendFormat": "{{ jobType }}"
    }
   ]
  },
  {
   "title": "Total jobs submitted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(job_dispatcher_jobs_created[$__range]))",
     "legendFormat": "Total Count:"
    }
   ]
  },
  {
   "title": "Jobs Being Processed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{pod=~\"create.*\", phase=~\"Pending|Running\"})",
     "legendFormat": "Count: "
    }
   ]
  },
  { "title": "Monitor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Completed Jobs Per Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (jobType, exitCode ) (rate(job_monitor_jobs_counter[1m])) * 60",
     "legendFormat": "{{ jobType }} wExit Code:{{ exitCode }}"
    }
   ]
  },
  {
   "title": "99th Percentile of Job completion Duration",
   "type": "graph",
   "description": "Duration is in seconds",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(job_monitor_jobs_duration_bucket[4m])) without (instance))",
     "legendFormat": "{{ jobType }} wExitCode: {{ exitCode}}"
    }
   ]
  },
  {
   "title": "Total jobs processed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(job_monitor_jobs_counter[$__range]))",
     "legendFormat": "Count:"
    }
   ]
  },
  {
   "title": "Pending + Ongoing Jobs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_job_info)", "legendFormat": "Count:" }
   ]
  }
 ]
}